# shellcheck shell=bash
# nas configure — the wizard (docs/wizard-spec.md). Fills shared.env and each
# selected unit's .env so install stays fully non-interactive. Optional (W1):
# install works from hand-edited files. Never touches generated or
# bootstrap-minted secrets (W2). Nothing is written until a file's staged
# diff is confirmed (W5).

ADVANCED=0
WRITTEN_FILES=""

cmd_configure() {
  local args=() arg
  for arg in "$@"; do
    case "$arg" in
      --advanced)   ADVANCED=1 ;;
      --dry-run)    DRY_RUN=1 ;;
      -h|--help)    configure_usage; return 0 ;;
      -*)           die "unknown flag '${arg}' for nas configure" ;;
      *)            args+=("$arg") ;;
    esac
  done

  # A wizard is prompts; without a terminal there is nothing it can do (W7).
  if ! is_tty; then
    echo "ERROR: nas configure is interactive and needs a terminal." >&2
    echo "       Edit the .env files by hand instead (from the .example files) —" >&2
    echo "       nas install runs headless." >&2
    exit 1
  fi

  if [ "${#args[@]}" -eq 0 ]; then
    ui_choose_multi $UNITS_ALL $UNITS_STANDALONE
    # shellcheck disable=SC2086
    select_units configure 1 $REPLY_VALUE
  else
    select_units configure 1 "${args[@]}"
  fi

  declare -gA STAGE_VAL STAGE_OLD STAGE_KEYS

  say "nas configuration wizard"
  info "mode: $([ "$ADVANCED" -eq 1 ] && echo 'advanced (every variable, with help text)' \
    || echo 'quick (detect + confirm; --advanced walks every variable)')"
  [ "$DRY_RUN" -eq 1 ] && info "dry run: full wizard, nothing will be written"
  info "units:$(selected_units)"
  info "Ctrl-C is safe — each file is written only after you confirm its summary."
  if [ "$IS_ROOT" -eq 1 ] && [ -z "${SUDO_UID:-}" ]; then
    warn "running as plain root — written .env files will be root-owned"
  fi

  trap 'printf "\n"; rm -f ./*.env.tmp pi-hole/.env.tmp 2>/dev/null; warn "interrupted — written:${WRITTEN_FILES:- nothing}; everything else untouched"; exit 130' INT

  wiz_detect
  wiz_prepare_files

  wiz_shared_section
  review_and_write shared

  wiz_media_dirs_section

  local unit
  for unit in $(selected_units); do
    unit_load "$unit"
    if unit_has_hook unit_configure; then
      say "${unit}"
      unit_configure
    fi
    [ "$ADVANCED" -eq 1 ] && wiz_walk "$unit"
    review_and_write "$unit"
  done

  say "Done"
  if [ "$DRY_RUN" -eq 1 ]; then
    info "dry run — nothing was written"
  else
    info "written:${WRITTEN_FILES:- nothing}"
  fi
  info "Next: sudo ./nas install$(want pihole && echo ' (pihole excluded: cd pi-hole && sudo docker compose up -d)')"
}

configure_usage() {
  cat <<EOF
nas configure [--advanced] [--dry-run] [unit...|all]

Guided setup of the .env files, meant to run before \`sudo ./nas install\`.
Detects host facts, asks once for the shared identity and the values units
must agree on (media directories), then walks each selected unit. Each file
is written only after its staged summary is confirmed; re-runs edit, never
reset. The generated secrets (API keys) are install's business, never
touched here.

  --advanced   walk every variable, with the example's help text
  --dry-run    full wizard, prints writes, changes nothing
EOF
}

# --- plumbing --------------------------------------------------------------------

wiz_env_path() {
  if [ "$1" = "shared" ]; then
    printf 'shared.env'
  else
    ( unit_load "$1" >/dev/null 2>&1; printf '%s' "$UNIT_ENV_FILE" )
  fi
}

wiz_get()         { env_get "$(wiz_env_path "$1")" "$2"; }
wiz_get_example() { env_get_example "$(wiz_env_path "$1")" "$2"; }

# Generated by install or minted by a bootstrap — load-bearing forever, never
# written, cleared, or displayed here (W2). ADMIN_PASSWORD is not in this
# set: it is a chosen credential with its own prompt.
wiz_is_secret() { # wiz_is_secret <file> <name>
  local protected
  if [ "$1" = "shared" ]; then
    protected=""
  else
    protected=$( unit_load "$1" >/dev/null 2>&1; printf '%s %s' "$UNIT_GENERATED" "$UNIT_MINTED" )
  fi
  case " $protected " in *" $2 "*) return 0 ;; esac
  return 1
}

stage() { # stage <file> <name> <value>
  local file="$1" name="$2" value="$3" k="${1}:${2}"
  if [ "$file" != "shared" ]; then want "$file" || return 0; fi
  if wiz_is_secret "$file" "$name"; then
    warn "refusing to stage ${name} — managed by nas install / the bootstraps"
    return 0
  fi
  if [ -z "${STAGE_VAL[$k]+x}" ]; then
    STAGE_KEYS[$file]="${STAGE_KEYS[$file]:-} ${name}"
    STAGE_OLD[$k]=$(wiz_get "$file" "$name")
  fi
  STAGE_VAL[$k]="$value"
}

staged() { # staged <file> <name> — is it already staged?
  [ -n "${STAGE_VAL[${1}:${2}]+x}" ]
}

wiz_ask() { # wiz_ask <prompt> <default> [validator] — result in REPLY_VALUE
  local prompt="$1" default="$2" validator="${3:-}"
  while :; do
    ui_input "$prompt" "$default" || continue
    if [ -n "$validator" ] && ! "$validator" "$REPLY_VALUE"; then continue; fi
    return 0
  done
}

# Masked, non-empty, confirmed twice — a typo in the admin password is only
# discovered after Jellyfin's one-shot wizard has closed around it (W6).
wiz_ask_secret() { # wiz_ask_secret <prompt> — result in REPLY_VALUE
  local val confirm
  while :; do
    ui_input_secret "$1"
    val="$REPLY_VALUE"
    if [ -z "$val" ]; then
      warn "cannot be empty"
      continue
    fi
    case "$val" in
      *"'"*'`'*|*'`'*"'"*)
        warn "cannot contain both a single quote and a backtick (shell and compose dotenv cannot agree on it)"
        continue ;;
    esac
    ui_input_secret "Confirm"
    confirm="$REPLY_VALUE"
    [ "$val" = "$confirm" ] && break
    warn "did not match, try again"
  done
  REPLY_VALUE="$val"
}

pick_default() { # pick_default <current> <example> <detected>
  # Detection wins only while the .env still holds the example's default — a
  # value the user changed by hand is never overridden by a probe (W3).
  if [ -n "$3" ] && [ "$1" = "$2" ]; then
    printf '%s' "$3"
  else
    printf '%s' "$1"
  fi
}

indexer_env_key() { # kinozal -> KINOZAL; must derive exactly as arr-indexers.sh
  printf '%s' "$1" | tr '[:lower:]' '[:upper:]' | tr -c 'A-Z0-9' '_'
}

# --- validators (each warns and returns 1 on bad input) ---------------------------

is_port() {
  case "$1" in
    ''|*[!0-9]*) ;;
    *) [ "$1" -ge 1 ] && [ "$1" -le 65535 ] && return 0 ;;
  esac
  warn "must be a port number 1-65535"; return 1
}
is_gid() {
  case "$1" in ''|*[!0-9]*) warn "must be numeric"; return 1 ;; esac
  return 0
}
is_abs_dir() {
  case "$1" in
    /*) case "/${1}/" in *"/../"*) ;; *) return 0 ;; esac ;;
  esac
  warn "must be an absolute path without .."; return 1
}
is_nonempty() {
  [ -n "$1" ] && return 0
  warn "cannot be empty"; return 1
}
is_01() {
  case "$1" in 0|1) return 0 ;; esac
  warn "must be 0 or 1"; return 1
}
is_subnet() { # a real CIDR check, not just shape — 999.9.9.9/99 must not pass
  local ip mask o n=0 ok=0
  case "$1" in
    *[!0-9./]*|''|*/*/*|/*|*/) ;;
    */*)
      ip="${1%/*}" mask="${1#*/}"
      ok=1
      case "$mask" in
        *[!0-9]*) ok=0 ;;
        *) { [ "${#mask}" -le 2 ] && [ "$mask" -le 32 ]; } || ok=0 ;;
      esac
      local IFS=.
      for o in $ip; do
        n=$((n + 1))
        { [ -n "$o" ] && [ "${#o}" -le 3 ] && [ "$o" -le 255 ]; } || ok=0
      done
      [ "$n" -eq 4 ] || ok=0 ;;
  esac
  [ "$ok" -eq 1 ] && return 0
  warn "must be IPv4 CIDR notation, e.g. 192.168.0.0/24"; return 1
}
is_seed_ratio() { # -1 means no cap (Session\GlobalMaxRatio)
  case "$1" in
    -1) return 0 ;;
    ''|*[!0-9.]*|*.*.*|.*|*.) ;;
    *) return 0 ;;
  esac
  warn "must be a ratio like 2 or 1.5, or -1 for no cap"; return 1
}
is_seed_minutes() {
  case "$1" in
    -1) return 0 ;;
    ''|*[!0-9]*) ;;
    *) return 0 ;;
  esac
  warn "must be a whole number of minutes, or -1 for no cap"; return 1
}
is_csv() {
  case "$1" in
    ''|*' '*) warn "comma-separated, no spaces"; return 1 ;;
    *[!A-Za-z0-9,._-]*) warn "definition names are letters/digits/._- only"; return 1 ;;
  esac
  return 0
}
is_defname() {
  case "$1" in
    ''|*[!A-Za-z0-9._-]*) warn "must be a single Prowlarr definition name"; return 1 ;;
  esac
  return 0
}
is_hosts_list() { # no wildcards or CIDR — Homepage matches each entry literally
  local v="$1" t
  if [ "$v" = "*" ]; then
    warn "'*' disables the Host check entirely — accepted, but listing hosts is safer"
    return 0
  fi
  if [ -z "$v" ]; then warn "cannot be empty"; return 1; fi
  local IFS=','
  for t in $v; do
    case "$t" in
      ''|*'*'*|*/*)
        warn "no wildcards or CIDR — each name/IP listed in full (got '${t}')"; return 1 ;;
      *[!A-Za-z0-9.-]*)
        warn "invalid host '${t}'"; return 1 ;;
    esac
  done
  return 0
}

validator_for() {
  case "$1" in
    *_PORT)                            printf 'is_port' ;;
    PUID|PGID|UMASK|*_GID)             printf 'is_gid' ;;
    *_DIR|*_ROOT_FOLDER)               printf 'is_abs_dir' ;;
    JELLYFIN_LOCAL_SUBNET|LAN_SUBNET)  printf 'is_subnet' ;;
    HOMEPAGE_ALLOWED_HOSTS)            printf 'is_hosts_list' ;;
    ARR_INDEXERS|ARR_INDEXERS_PRIVATE) printf 'is_csv' ;;
    QBITTORRENT_SEED_RATIO)            printf 'is_seed_ratio' ;;
    QBITTORRENT_SEED_MINUTES)          printf 'is_seed_minutes' ;;
    JELLYFIN_SCAN_ON_BOOTSTRAP|JELLYFIN_INSTALL_DLNA) printf 'is_01' ;;
    ARR_INSTALL_INDEXERS|ARR_RUN_CONFIGARR|SEERR_CONFIGURE) printf 'is_01' ;;
    *)                                 printf '' ;;
  esac
}

# --- detection (each probe degrades to empty — nothing here may be fatal) ---------

detect_tz() {
  if [ -r /etc/timezone ]; then
    tr -d '[:space:]' < /etc/timezone
    return 0
  fi
  if [ -L /etc/localtime ]; then
    readlink /etc/localtime 2>/dev/null | sed 's|.*/zoneinfo/||'
  fi
  return 0
}
detect_docker_gid() {
  command -v getent >/dev/null 2>&1 || return 0
  getent group docker 2>/dev/null | cut -d: -f3 || true
  return 0
}
detect_render_gid() {
  if [ -e /dev/dri/renderD128 ]; then
    stat -c %g /dev/dri/renderD128 2>/dev/null && return 0
  fi
  command -v getent >/dev/null 2>&1 || return 0
  getent group render 2>/dev/null | cut -d: -f3 || true
  return 0
}
detect_lan_ip() {
  local out=""
  if command -v ip >/dev/null 2>&1; then
    out=$(ip route get 1.1.1.1 2>/dev/null \
      | awk '{for(i=1;i<NF;i++) if($i=="src"){print $(i+1); exit}}') || out=""
  fi
  if [ -z "$out" ]; then
    out=$(hostname -I 2>/dev/null | awk '{print $1}') || out=""
  fi
  printf '%s' "$out"
  return 0
}
detect_hostname() {
  local h
  h=$(hostname -s 2>/dev/null) || h=""
  [ -n "$h" ] && printf '%s.local' "$h"
  return 0
}

wiz_detect() {
  DET_TZ=$(detect_tz)
  DET_DOCKER_GID=$(detect_docker_gid)
  DET_RENDER_GID=$(detect_render_gid)
  DET_LAN_IP=$(detect_lan_ip)
  DET_HOSTNAME=$(detect_hostname)
  say "Detected host facts"
  local show
  show() { info "$1: ${2:-"(not detected — keeping current values)"}"; }
  show "timezone   " "$DET_TZ"
  show "docker GID " "$DET_DOCKER_GID"
  show "render GID " "$DET_RENDER_GID"
  show "LAN IP     " "$DET_LAN_IP"
  show "hostname   " "$DET_HOSTNAME"
}

# --- drift against the examples ----------------------------------------------------

# A variable new in the example is staged at the example default; a variable
# the example dropped is warned about, never deleted.
wiz_drift_sync() { # wiz_drift_sync <file-key>
  local file="$1" path var
  path=$(wiz_env_path "$file")
  [ -f "$path" ] || return 0
  for var in $(example_vars "$path"); do
    wiz_is_secret "$file" "$var" && continue
    grep -q "^${var}=" "$path" && continue
    info "${path} is missing ${var} (new in the example) — staging the default"
    stage "$file" "$var" "$(env_get_example "$path" "$var")"
  done
  # shellcheck disable=SC2013
  for var in $(grep -E '^[A-Z][A-Z0-9_]*=' "$path" | cut -d= -f1); do
    grep -q "^${var}=" "${path}.example" && continue
    case "$var" in ARR_INDEXER_*) continue ;; esac   # custom tracker credentials
    warn "${path} has ${var}, which is not in the example — kept as-is"
  done
  return 0
}

wiz_prepare_files() {
  say "Preparing .env files"
  local file path
  for file in shared $(selected_units); do
    path=$(wiz_env_path "$file")
    [ -f "${path}.example" ] || continue
    if [ -f "$path" ]; then
      info "${path} exists — its values are the defaults below"
    elif [ "$DRY_RUN" -eq 1 ]; then
      info "[dry-run] ${path} would be created from ${path}.example"
    else
      info "${path} will be created from ${path}.example when confirmed"
    fi
    wiz_drift_sync "$file"
  done
}

# --- sections ----------------------------------------------------------------------

wiz_shared_section() {
  say "Shared settings"
  local cur ex def

  cur=$(wiz_get shared TZ); ex=$(wiz_get_example shared TZ)
  def=$(pick_default "$cur" "$ex" "$DET_TZ")
  if [ "$ADVANCED" -eq 1 ]; then
    wiz_ask "TZ" "$def" is_nonempty
    def="$REPLY_VALUE"
  fi
  stage shared TZ "$def"

  cur=$(wiz_get shared PUID)
  if [ "$ADVANCED" -eq 1 ]; then
    info "PUID/PGID: the user and group every service runs as."
    wiz_ask "PUID" "$cur" is_gid; stage shared PUID "$REPLY_VALUE"
    wiz_ask "PGID" "$(wiz_get shared PGID)" is_gid; stage shared PGID "$REPLY_VALUE"
  else
    stage shared PUID "$cur"
    stage shared PGID "$(wiz_get shared PGID)"
  fi

  cur=$(wiz_get shared DOCKER_GID); ex=$(wiz_get_example shared DOCKER_GID)
  def=$(pick_default "$cur" "$ex" "$DET_DOCKER_GID")
  if [ -z "$DET_DOCKER_GID" ]; then
    info "docker group GID not detectable here — confirm with: getent group docker"
  fi
  if [ "$ADVANCED" -eq 1 ]; then
    wiz_ask "DOCKER_GID" "$def" is_gid
    def="$REPLY_VALUE"
  fi
  stage shared DOCKER_GID "$def"

  cur=$(wiz_get shared LAN_HOST); ex=$(wiz_get_example shared LAN_HOST)
  def=$(pick_default "$cur" "$ex" "$DET_LAN_IP")
  info "How a container reaches something host-networked (Jellyfin) or the host"
  info "itself: the Jellyfin Homepage widget and Seerr's Jellyfin sign-in both use it."
  if [ "$ADVANCED" -eq 1 ]; then
    wiz_ask "LAN_HOST" "$def" is_nonempty
    def="$REPLY_VALUE"
  fi
  stage shared LAN_HOST "$def"

  # The shared identity: Jellyfin admin + qBittorrent WebUI + Seerr (which
  # rides it via /auth/jellyfin) — only worth asking when a consumer is in
  # scope. shared.env stays the single source of truth; no consumer ever
  # holds a copy the file doesn't (wizard-spec §Future).
  if want jellyfin || want qbittorrent || want seerr; then
    wiz_ask "Admin username (ADMIN_USER) — Jellyfin admin + qBittorrent WebUI login" \
      "$(wiz_get shared ADMIN_USER)" is_nonempty
    stage shared ADMIN_USER "$REPLY_VALUE"

    cur=$(wiz_get shared ADMIN_PASSWORD)
    if [ -n "$cur" ]; then
      if ! ui_confirm "ADMIN_PASSWORD is already set — keep it?" Y; then
        wiz_ask_secret "New admin password"
        wiz_stage_admin_password "$REPLY_VALUE"
      fi
    else
      info "Jellyfin's setup wizard is one-shot — a password typo is only discovered"
      info "after the wizard has closed around it, so this is confirmed twice."
      wiz_ask_secret "Admin password"
      wiz_stage_admin_password "$REPLY_VALUE"
    fi
  fi

  [ "$ADVANCED" -eq 1 ] && wiz_walk shared
  return 0
}

wiz_stage_admin_password() {
  [ "${#1}" -lt 12 ] && warn "under 12 characters — fine on a LAN-only box, but longer is better"
  stage shared ADMIN_PASSWORD "$1"
}

# Media directories asked once and staged into every consumer: the jellyfin
# MEDIA_*_DIR and the arr units' ARR_*_DIR are separate files holding the
# same underlying host path, and must stay identical. unmanic's UNMANIC_*_DIR
# joins the same rule.
wiz_media_dirs_section() {
  { want jellyfin || want radarr || want sonarr || want lidarr || want unmanic; } || return 0
  say "Media libraries (pre-existing — never created or chowned by install)"

  if want jellyfin || want radarr || want unmanic; then
    local cur=""
    if want jellyfin; then cur=$(wiz_get jellyfin MEDIA_MOVIES_DIR)
    elif want radarr; then cur=$(wiz_get radarr ARR_MOVIES_DIR)
    else cur=$(wiz_get unmanic UNMANIC_MOVIES_DIR)
    fi
    wiz_ask "Movies directory" "$cur" is_abs_dir
    [ -d "$REPLY_VALUE" ] || warn "does not exist yet — that library will start empty"
    want jellyfin && stage jellyfin MEDIA_MOVIES_DIR "$REPLY_VALUE"
    want radarr   && stage radarr   ARR_MOVIES_DIR   "$REPLY_VALUE"
    want unmanic  && stage unmanic  UNMANIC_MOVIES_DIR "$REPLY_VALUE"
  fi

  if want jellyfin || want sonarr || want unmanic; then
    local cur=""
    if want jellyfin; then cur=$(wiz_get jellyfin MEDIA_SERIES_DIR)
    elif want sonarr; then cur=$(wiz_get sonarr ARR_SERIES_DIR)
    else cur=$(wiz_get unmanic UNMANIC_SERIES_DIR)
    fi
    wiz_ask "Series directory" "$cur" is_abs_dir
    [ -d "$REPLY_VALUE" ] || warn "does not exist yet — that library will start empty"
    want jellyfin && stage jellyfin MEDIA_SERIES_DIR "$REPLY_VALUE"
    want sonarr   && stage sonarr   ARR_SERIES_DIR   "$REPLY_VALUE"
    want unmanic  && stage unmanic  UNMANIC_SERIES_DIR "$REPLY_VALUE"
  fi

  if want jellyfin || want lidarr; then
    local cur=""
    if want jellyfin; then cur=$(wiz_get jellyfin MEDIA_MUSIC_DIR)
    else cur=$(wiz_get lidarr ARR_MUSIC_DIR)
    fi
    wiz_ask "Music directory" "$cur" is_abs_dir
    [ -d "$REPLY_VALUE" ] || warn "does not exist yet — that library will start empty"
    want jellyfin && stage jellyfin MEDIA_MUSIC_DIR "$REPLY_VALUE"
    want lidarr   && stage lidarr   ARR_MUSIC_DIR   "$REPLY_VALUE"
  fi
  return 0
}

# --- advanced walk -----------------------------------------------------------------

wiz_walk() { # wiz_walk <file-key> — every example var not already handled
  local file="$1" path var help cur
  path=$(wiz_env_path "$file")
  for var in $(example_vars "$path"); do
    wiz_is_secret "$file" "$var" && continue
    staged "$file" "$var" && continue
    case "$var" in *PASSWORD*|*_PASS) continue ;; esac   # owned by dedicated prompts
    help=$(env_help_for "$path" "$var")
    if [ -n "$help" ]; then
      printf '\n'
      printf '%s\n' "$help" | sed 's/^#/    /'
    fi
    cur=$(env_get "$path" "$var")
    wiz_ask "$var" "$cur" "$(validator_for "$var")"
    stage "$file" "$var" "$REPLY_VALUE"
    case "$var" in
      *_CONFIG_DIR|DOWNLOADS_DIR)
        case "$REPLY_VALUE" in
          "${SAFE_ROOT}"/*) ;;
          *) warn "outside ${SAFE_ROOT} — nas destroy will refuse to clean it (R1)" ;;
        esac ;;
      QBITTORRENT_SEED_RATIO|QBITTORRENT_SEED_MINUTES)
        [ "$REPLY_VALUE" = "$cur" ] \
          || warn "applied via qBittorrent.conf at first start only — a change here does not reach a running qBittorrent" ;;
    esac
  done
}

# --- staging review + write --------------------------------------------------------

wiz_disp() { # wiz_disp <name> <value> — passwords masked
  local shown="$2"
  case "$1" in
    *PASSWORD*|*_PASS) [ -n "$2" ] && shown='********' ;;
  esac
  [ -n "$shown" ] && printf '%s' "$shown" || printf '(empty)'
}

print_stage() { # print_stage <file-key>
  local file="$1" i=0 name val old
  printf '\n'
  for name in ${STAGE_KEYS[$file]:-}; do
    i=$((i + 1))
    val="${STAGE_VAL[${file}:${name}]}"
    old="${STAGE_OLD[${file}:${name}]}"
    if [ "$val" != "$old" ]; then
      printf '    %2d) %-28s = %s  \033[33m(was: %s)\033[0m\n' \
        "$i" "$name" "$(wiz_disp "$name" "$val")" "$(wiz_disp "$name" "$old")"
    else
      printf '    %2d) %-28s = %s\n' "$i" "$name" "$(wiz_disp "$name" "$val")"
    fi
  done
}

stage_name_at() { # stage_name_at <file-key> <index-1-based>
  local i=0 name
  for name in ${STAGE_KEYS[$1]:-}; do
    i=$((i + 1))
    [ "$i" -eq "$2" ] && { printf '%s' "$name"; return 0; }
  done
  return 1
}

stage_count() {
  local n=0 _name
  for _name in ${STAGE_KEYS[$1]:-}; do n=$((n + 1)); done
  printf '%s' "$n"
}

review_and_write() { # review_and_write <file-key>
  local file="$1" n ans idx name vfun path
  if [ "$file" != "shared" ]; then want "$file" || return 0; fi
  n=$(stage_count "$file")
  [ "$n" -eq 0 ] && return 0
  path=$(wiz_env_path "$file")
  say "Review — ${path}"
  print_stage "$file"
  case "$file" in
    sonarr|radarr|lidarr|prowlarr|seerr)
      info "(the ${file} API key is generated by nas install, never here)" ;;
    jellyfin)
      info "(JELLYFIN_API_KEY / JELLYFIN_SCAN_TASK_ID are minted by jellyfin-bootstrap.sh, never here)" ;;
  esac
  while :; do
    printf '\n    [Enter] write   e <n> edit item   s skip this file   q quit: '
    IFS= read -r ans
    case "$ans" in
      '') wiz_write_file "$file"; return 0 ;;
      s)  warn "skipped — nothing written to ${path}"; return 0 ;;
      q)  warn "quit — written so far:${WRITTEN_FILES:- nothing}"; exit 1 ;;
      e*)
        idx="${ans#e}"
        idx="${idx//[[:space:]]/}"
        case "$idx" in ''|*[!0-9]*) warn "usage: e <item number>"; continue ;; esac
        if [ "$idx" -lt 1 ] || [ "$idx" -gt "$n" ]; then
          warn "no item ${idx}"
          continue
        fi
        name=$(stage_name_at "$file" "$idx")
        case "$name" in
          *PASSWORD*|*_PASS) wiz_ask_secret "New value for ${name}" ;;
          *)
            vfun=$(validator_for "$name")
            wiz_ask "$name" "${STAGE_VAL[${file}:${name}]}" "$vfun" ;;
        esac
        STAGE_VAL[${file}:${name}]="$REPLY_VALUE"
        print_stage "$file" ;;
      *) warn "unrecognized: ${ans}" ;;
    esac
  done
}

wiz_write_file() { # wiz_write_file <file-key>
  local file="$1" path name val shown n
  path=$(wiz_env_path "$file")
  n=$(stage_count "$file")
  if [ "$DRY_RUN" -eq 0 ]; then
    if [ ! -f "$path" ]; then
      cp "${path}.example" "$path"
      repo_own "$path"
      info "${path} created from ${path}.example"
    fi
    # These carry a password, an API key, or private-tracker credentials.
    case "$file" in
      shared|jellyfin|sonarr|radarr|lidarr|prowlarr|seerr|pihole) chmod 600 "$path" ;;
    esac
  fi
  for name in ${STAGE_KEYS[$file]:-}; do
    val="${STAGE_VAL[${file}:${name}]}"
    if [ "$DRY_RUN" -eq 1 ]; then
      # Not wiz_disp: an empty value must print as NAME= (what would be
      # written), not as the review table's "(empty)" placeholder.
      shown="$val"
      case "$name" in *PASSWORD*|*_PASS) [ -n "$val" ] && shown='********' ;; esac
      printf '    [dry-run] %s: %s=%s\n' "$path" "$name" "$shown"
    else
      env_set "$path" "$name" "$val"
    fi
  done
  if [ "$DRY_RUN" -eq 0 ]; then
    repo_own "$path"
    info "${n} value(s) written to ${path}"
    WRITTEN_FILES="${WRITTEN_FILES} ${path}"
  fi
}
