# shellcheck shell=bash
UNIT_PORT=8686
UNIT_PORT_VAR=LIDARR_PORT
UNIT_DIRS="LIDARR_CONFIG_DIR DOWNLOADS_DIR DOWNLOADS_DIR/complete DOWNLOADS_DIR/incomplete"
UNIT_CHECK_DIRS="ARR_MUSIC_DIR:w"
UNIT_GENERATED="LIDARR_API_KEY"
UNIT_REQUIRED="LIDARR_API_KEY"
UNIT_POST_INSTALL="arr"
