# shellcheck shell=bash
UNIT_PORT=7878
UNIT_PORT_VAR=RADARR_PORT
UNIT_DIRS="RADARR_CONFIG_DIR DOWNLOADS_DIR DOWNLOADS_DIR/complete DOWNLOADS_DIR/incomplete"
UNIT_CHECK_DIRS="ARR_MOVIES_DIR:w"
UNIT_GENERATED="RADARR_API_KEY"
UNIT_REQUIRED="RADARR_API_KEY"
UNIT_POST_INSTALL="arr"
