# shellcheck shell=bash
UNIT_PORT=5055
UNIT_PORT_VAR=SEERR_PORT
UNIT_DIRS="SEERR_CONFIG_DIR"
UNIT_GENERATED="SEERR_API_KEY"
UNIT_REQUIRED="SEERR_API_KEY ADMIN_PASSWORD"
UNIT_POST_INSTALL="seerr-bootstrap.sh"
