# shellcheck shell=bash
UNIT_PORT=8989
UNIT_PORT_VAR=SONARR_PORT
UNIT_DIRS="SONARR_CONFIG_DIR DOWNLOADS_DIR DOWNLOADS_DIR/complete DOWNLOADS_DIR/incomplete"
UNIT_CHECK_DIRS="ARR_SERIES_DIR:w"
UNIT_GENERATED="SONARR_API_KEY"
UNIT_REQUIRED="SONARR_API_KEY"
UNIT_POST_INSTALL="arr"
