# shellcheck shell=bash
UNIT_PORT=8888
UNIT_PORT_VAR=UNMANIC_PORT
UNIT_DIRS="UNMANIC_CONFIG_DIR UNMANIC_CACHE_DIR"
UNIT_CHECK_DIRS="UNMANIC_MOVIES_DIR:w UNMANIC_SERIES_DIR:w"
UNIT_LOG_PATHS="UNMANIC_CONFIG_DIR/.unmanic/logs"
UNIT_POST_INSTALL="unmanic-bootstrap.sh"
